<?php

function createGlobalColorArray(): array
{
  //    $colors[>Select Background</option> "
    $colors["#F0F8FF"] = "aliceblue";
    $colors["#FAEBD7"] = "antiquewhite";
    $colors["#00FFFE"] = "aqua";

    $colors["#7FFFD4"] = "aquamarine";
    $colors["#F0FFFF"] = "azure";
    $colors["#F5F5DC"] = "beige";
    $colors["#FFE4C4"] = "bisque";
    $colors["#000000"] = "black";
    $colors["#FFEBCD"] = "blanchedalmond";
    $colors["#0000FF"] = "blue";
    $colors["#8A2BE2"] = "blueviolet";
    $colors["#A52A2A"] = "brown";

    $colors["#DEB887"] = "burlywood";
    $colors["#5F9EA0"] = "cadetblue";
    $colors["#7FFF00"] = "chartreuse";
    $colors["#D2691E"] = "chocolate";
    $colors["#FF7F50"] = "coral";
    $colors["#6495ED"] = "cornflowerblue";
    $colors["#FFF8DC"] = "cornsilk";
    $colors["#DC143C"] = "crimson";
    $colors["#00FFFF"] = "cyan";

    $colors["#00008B"] = "darkblue";
    $colors["#008B8B"] = "darkcyan";
    $colors["#B8860B"] = "darkgoldenrod";
    $colors["#A9A9A9"] = "darkgray";
    $colors["#006400"] = "darkgreen";
    $colors["#BDB76B"] = "darkkhaki";
    $colors["#8B008B"] = "darkmagenta";
    $colors["#556B2F"] = "darkolivegreen";
    $colors["#FF8C00"] = "darkorange";

    $colors["#9932CC"] = "darkorchid";
    $colors["#8B0000"] = "darkred";
    $colors["#E9967A"] = "darksalmon";
    $colors["#8FBC8F"] = "darkseagreen";
    $colors["#483D8B"] = "darkslateblue";
    $colors["#2F4F4F"] = "darkslategray";
    $colors["#00CED1"] = "darkturquoise";
    $colors["#9400D3"] = "darkviolet";
    $colors["#FF1493"] = "deeppink";

    $colors["#00BFFF"] = "deepskyblue";
    $colors["#696969"] = "dimgray";
    $colors["#1E90FF"] = "dodgerblue";
    $colors["#B22222"] = "firebrick";
    $colors["#FFFAF0"] = "floralwhite";
    $colors["#228B22"] = "forestgreen";
    $colors["#FF00FE"] = "fuchsia";
    $colors["#DCDCDC"] = "gainsboro";
    $colors["#F8F8FF"] = "ghostwhite";

    $colors["#FFD700"] = "gold";
    $colors["#DAA520"] = "goldenrod";
    $colors["#BEBEBE"] = "gray";
    $colors["#008000"] = "green";
    $colors["#ADFF2F"] = "greenyellow";
    $colors["#F0FFF0"] = "honeydew";
    $colors["#FF69B4"] = "hotpink";
    $colors["#CD5C5C"] = "indianred";
    $colors["#4B0082"] = "indigo";

    $colors["#FFFFF0"] = "ivory";
    $colors["#F0D58C"] = "khaki";
    $colors["#E6E6FA"] = "lavender";
    $colors["#FFF0F5"] = "lavenderblush";
    $colors["#7CFC00"] = "lawngreen";
    $colors["#FFFACD"] = "lemonchiffon";
    $colors["#ADD8E6"] = "lightblue";
    $colors["#F08080"] = "lightcoral";
    $colors["#E0FFFF"] = "lightcyan";

    $colors["#FAFAD2"] = "lightgoldenrodyellow";
    $colors["#90EE90"] = "lightgreen";
    $colors["#D3D3D3"] = "lightgrey";
    $colors["#FFB6C1"] = "lightpink";
    $colors["#FFA07A"] = "lightsalmon";
    $colors["#20B2AA"] = "lightseagreen";
    $colors["#87CEFA"] = "lightskyblue";
    $colors["#778899"] = "lightslategray";
    $colors["#B0C4DE"] = "lightsteelblue";

    $colors["#FFFFE0"] = "lightyellow";
    $colors["#00FF00"] = "lime";
    $colors["#32CD32"] = "limegreen";
    $colors["#FAF0E6"] = "linen";
    $colors["#FF00FF"] = "magenta";
    $colors["#800000"] = "maroon";
    $colors["#66CDAA"] = "mediumaquamarine";
    $colors["#0000CD"] = "mediumblue";
    $colors["#BA55D3"] = "mediumorchid";

    $colors["#9370DB"] = "mediumpurple";
    $colors["#3CB371"] = "mediumseagreen";
    $colors["#7B68EE"] = "mediumslateblue";
    $colors["#00FA9A"] = "mediumspringgreen";
    $colors["#48D1CC"] = "mediumturquoise";
    $colors["#C71585"] = "mediumvioletred";
    $colors["#191970"] = "midnightblue";
    $colors["#F5FFFA"] = "mintcream";
    $colors["#FF44E1"] = "mistyrose";

    $colors["#FFE48B"] = "moccasin";
    $colors["#FFDEAD"] = "navajowhite";
    $colors["#000080"] = "navy";
    $colors["#FDF5E6"] = "oldlace";
    $colors["#808000"] = "olive";
    $colors["#6B8E23"] = "olivedrab";
    $colors["#FFA500"] = "orange";
    $colors["#FF4500"] = "orangered";
    $colors["#DA70D6"] = "orchid";

    $colors["#EEE8AA"] = "palegoldenrod";
    $colors["#98FB98"] = "palegreen";
    $colors["#AFEEEE"] = "paleturquoise";
    $colors["#DB7093"] = "palevioletred";
    $colors["#FFEFD5"] = "papayawhip";
    $colors["#FFDAB9"] = "peachpuff";
    $colors["#CD853F"] = "peru";
    $colors["#FFC0CB"] = "pink";
    $colors["#DDA0DD"] = "plum";

    $colors["#B0E0E6"] = "powderblue";
    $colors["#800080"] = "purple";
    $colors["#FF0000"] = "red";
    $colors["#BC8F8F"] = "rosybrown";
    $colors["#4169E1"] = "royalblue";
    $colors["#8B4513"] = "saddlebrown";
    $colors["#FA8072"] = "salmon";
    $colors["#F4A460"] = "sandybrown";
    $colors["#2E8B57"] = "seagreen";

    $colors["#FFF5EE"] = "seashell";
    $colors["#A0522D"] = "sienna";
    $colors["#C0C0C0"] = "silver";
    $colors["#87CEEB"] = "skyblue";
    $colors["#6A5ACD"] = "slateblue";
    $colors["#708090"] = "slategray";
    $colors["#FFFAFA"] = "snow";
    $colors["#00FF7F"] = "springgreen";
    $colors["#4682B4"] = "steelblue";

    $colors["#D2B48C"] = "tan";
    $colors["#008080"] = "teal";
    $colors["#D8BFD8"] = "thistle";
    $colors["#FF6347"] = "tomato";
    $colors["#40E0D0"] = "turquoise";
    $colors["#EE82EE"] = "violet";
    $colors["#F5DEB3"] = "wheat";
    $colors["#FFFFFF"] = "white";
    $colors["#F5F5F5"] = "whitesmoke";

    $colors["#FFFF00"] = "yellow";
    $colors["#9ACD32"] = "yellowgreen";

    return $colors;
}

function shuffle_all_different($array) {

    $keys = array_keys($array); //Store the keys
    $values = array_values($array); // Cause we need a clean numeric array for this kind of randomisation
    for($i = count($values) - 1; $i > 0; $i--) {
        $r = mt_rand(0, $i-1); //subtract 1 from $i to force a new place.
        $tmp = $values[$i];
        $values[$i] = $values[$r];
        $values[$r] = $tmp;

        $tmp = $keys[$i];
        $keys[$i] = $keys[$r];
        $keys[$r] = $tmp;
    }
    //Now recombine keys and values
    return array_combine($keys, $values);
}

function shuffle_assoc($list): array {
    if (!is_array($list)) return $list;

    $keys = array_keys($list);
    shuffle($keys);
    $random = array();
    foreach ($keys as $key) {
        $random[$key] = $list[$key];
    }
    return $random;
}

function getShuffledColorArray(): array {
    $colors = createGlobalColorArray();
    $background_colors = shuffle_assoc($colors);
    $text_colors = shuffle_all_different($background_colors);
    return [$background_colors, $text_colors];
}

function getColorDDLB($name, $selected, &$colors): string {
  $ret = " <select name=\"" . $name . "\" > ";

  foreach ($colors as $htmlCode => $color) {
    $ret .= "<option ";
    if ( $selected == $htmlCode ) {
      $ret .= "selected=\"selected\" ";
    }
    $ret .= " value=\"" . $htmlCode . "\">" . $color;
  }
  reset($colors); // Needed after call to each()
  $ret .= "</option> ";

  //**/d("ret is [<pre>" . $ret . "</pre>]");
  return $ret;
}
