<?php

function createGlobalColourArray() {

  //    $colours[>Select Background</option> "
    $colours["#F0F8FF"] = "aliceblue";
    $colours["#FAEBD7"] = "antiquewhite";
    $colours["#00FFFF"] = "aqua";

    $colours["#7FFFD4"] = "aquamarine";
    $colours["#F0FFFF"] = "azure";
    $colours["#F5F5DC"] = "beige";
    $colours["#FFE4C4"] = "bisque";
    $colours["#000000"] = "black";
    $colours["#FFEBCD"] = "blanchedalmond";
    $colours["#0000FF"] = "blue";
    $colours["#8A2BE2"] = "blueviolet";
    $colours["#A52A2A"] = "brown";

    $colours["#DEB887"] = "burlywood";
    $colours["#5F9EA0"] = "cadetblue";
    $colours["#7FFF00"] = "chartreuse";
    $colours["#D2691E"] = "chocolate";
    $colours["#FF7F50"] = "coral";
    $colours["#6495ED"] = "cornflowerblue";
    $colours["#FFF8DC"] = "cornsilk";
    $colours["#DC143C"] = "crimson";
    $colours["#00FFFF"] = "cyan";

    $colours["#00008B"] = "darkblue";
    $colours["#008B8B"] = "darkcyan";
    $colours["#B8860B"] = "darkgoldenrod";
    $colours["#A9A9A9"] = "darkgray";
    $colours["#006400"] = "darkgreen";
    $colours["#BDB76B"] = "darkkhaki";
    $colours["#8B008B"] = "darkmagenta";
    $colours["#556B2F"] = "darkolivegreen";
    $colours["#FF8C00"] = "darkorange";

    $colours["#9932CC"] = "darkorchid";
    $colours["#8B0000"] = "darkred";
    $colours["#E9967A"] = "darksalmon";
    $colours["#8FBC8F"] = "darkseagreen";
    $colours["#483D8B"] = "darkslateblue";
    $colours["#2F4F4F"] = "darkslategray";
    $colours["#00CED1"] = "darkturquoise";
    $colours["#9400D3"] = "darkviolet";
    $colours["#FF1493"] = "deeppink";

    $colours["#00BFFF"] = "deepskyblue";
    $colours["#696969"] = "dimgray";
    $colours["#1E90FF"] = "dodgerblue";
    $colours["#B22222"] = "firebrick";
    $colours["#FFFAF0"] = "floralwhite";
    $colours["#228B22"] = "forestgreen";
    $colours["#FF00FF"] = "fuchsia";
    $colours["#DCDCDC"] = "gainsboro";
    $colours["#F8F8FF"] = "ghostwhite";

    $colours["#FFD700"] = "gold";
    $colours["#DAA520"] = "goldenrod";
    $colours["#BEBEBE"] = "gray";
    $colours["#008000"] = "green";
    $colours["#ADFF2F"] = "greenyellow";
    $colours["#F0FFF0"] = "honeydew";
    $colours["#FF69B4"] = "hotpink";
    $colours["#CD5C5C"] = "indianred";
    $colours["#4B0082"] = "indigo";

    $colours["#FFFFF0"] = "ivory";
    $colours["#F0D58C"] = "khaki";
    $colours["#E6E6FA"] = "lavender";
    $colours["#FFF0F5"] = "lavenderblush";
    $colours["#7CFC00"] = "lawngreen";
    $colours["#FFFACD"] = "lemonchiffon";
    $colours["#ADD8E6"] = "lightblue";
    $colours["#F08080"] = "lightcoral";
    $colours["#E0FFFF"] = "lightcyan";

    $colours["#FAFAD2"] = "lightgoldenrodyellow";
    $colours["#90EE90"] = "lightgreen";
    $colours["#D3D3D3"] = "lightgrey";
    $colours["#FFB6C1"] = "lightpink";
    $colours["#FFA07A"] = "lightsalmon";
    $colours["#20B2AA"] = "lightseagreen";
    $colours["#87CEFA"] = "lightskyblue";
    $colours["#778899"] = "lightslategray";
    $colours["#B0C4DE"] = "lightsteelblue";

    $colours["#FFFFE0"] = "lightyellow";
    $colours["#00FF00"] = "lime";
    $colours["#32CD32"] = "limegreen";
    $colours["#FAF0E6"] = "linen";
    $colours["#FF00FF"] = "magenta";
    $colours["#800000"] = "maroon";
    $colours["#66CDAA"] = "mediumaquamarine";
    $colours["#0000CD"] = "mediumblue";
    $colours["#BA55D3"] = "mediumorchid";

    $colours["#9370DB"] = "mediumpurple";
    $colours["#3CB371"] = "mediumseagreen";
    $colours["#7B68EE"] = "mediumslateblue";
    $colours["#00FA9A"] = "mediumspringgreen";
    $colours["#48D1CC"] = "mediumturquoise";
    $colours["#C71585"] = "mediumvioletred";
    $colours["#191970"] = "midnightblue";
    $colours["#F5FFFA"] = "mintcream";
    $colours["#FF44E1"] = "mistyrose";

    $colours["#FFE48B"] = "moccasin";
    $colours["#FFDEAD"] = "navajowhite";
    $colours["#000080"] = "navy";
    $colours["#FDF5E6"] = "oldlace";
    $colours["#808000"] = "olive";
    $colours["#6B8E23"] = "olivedrab";
    $colours["#FFA500"] = "orange";
    $colours["#FF4500"] = "orangered";
    $colours["#DA70D6"] = "orchid";

    $colours["#EEE8AA"] = "palegoldenrod";
    $colours["#98FB98"] = "palegreen";
    $colours["#AFEEEE"] = "paleturquoise";
    $colours["#DB7093"] = "palevioletred";
    $colours["#FFEFD5"] = "papayawhip";
    $colours["#FFDAB9"] = "peachpuff";
    $colours["#CD853F"] = "peru";
    $colours["#FFC0CB"] = "pink";
    $colours["#DDA0DD"] = "plum";

    $colours["#B0E0E6"] = "powderblue";
    $colours["#800080"] = "purple";
    $colours["#FF0000"] = "red";
    $colours["#BC8F8F"] = "rosybrown";
    $colours["#4169E1"] = "royalblue";
    $colours["#8B4513"] = "saddlebrown";
    $colours["#FA8072"] = "salmon";
    $colours["#F4A460"] = "sandybrown";
    $colours["#2E8B57"] = "seagreen";

    $colours["#FFF5EE"] = "seashell";
    $colours["#A0522D"] = "sienna";
    $colours["#C0C0C0"] = "silver";
    $colours["#87CEEB"] = "skyblue";
    $colours["#6A5ACD"] = "slateblue";
    $colours["#708090"] = "slategray";
    $colours["#FFFAFA"] = "snow";
    $colours["#00FF7F"] = "springgreen";
    $colours["#4682B4"] = "steelblue";

    $colours["#D2B48C"] = "tan";
    $colours["#008080"] = "teal";
    $colours["#D8BFD8"] = "thistle";
    $colours["#FF6347"] = "tomato";
    $colours["#40E0D0"] = "turquoise";
    $colours["#EE82EE"] = "violet";
    $colours["#F5DEB3"] = "wheat";
    $colours["#FFFFFF"] = "white";
    $colours["#F5F5F5"] = "whitesmoke";

    $colours["#FFFF00"] = "yellow";
    $colours["#9ACD32"] = "yellowgreen";

    return $colours;
  
}

function getColourDDLB($name, $selected, &$colours) {
  /*
    d("getColourDDLB(): name is [" . $name
    . "], selected is [" . $selected
    . "], count(colours) is [" . count($colours)
    . "]");
    */
  $ret = " <select name=\"" . $name . "\" > ";

  while ( list($htmlCode, $colour) = each($colours) ) {
    $ret .= "<option ";
    if ( $selected == $htmlCode ) {
      $ret .= "selected=\"selected\" ";
    }
    $ret .= " value=\"" . $htmlCode . "\">" . $colour;
  }
  reset($colours); // Needed after call to each()
  $ret .= "</option> ";

  //**/d("ret is [<pre>" . $ret . "</pre>]");
  return $ret;
}

?>